### ISSUE TITLE
Cannot scrape anything

### ISSUE THREAD

**Issue by grexzen** [alexakayman/morphix#1]
Cool repo! 

Tried a couple sites, like this https://platform.openai.com/docs/quickstart. 

And all the values come back null.

**Comment by alexakayman** [comment]
Hey sorry to hear about this @grexzen - could you specify what fields you submitted? Make sure to hit "Save" after entering the fields as well.

Troubleshooting/fixing in the meantime: The program deletes any non-text elements before scraping. This is to prevent .svg codes, images, video sources, iframes, etc. from taking up the character limit when making the openAI request. The docs are definitely text, but the surrounding Playgrounds may be causing the issue. Looking into this.

**Comment by grexzen** [comment]
Thanks. I tried many ways, but everything comes back null. 

![image](https://github.com/alexakayman/morphix/assets/30579087/593aa7fd-a52f-4a4a-be35-4006ca41e8e0)

**Comment by alexakayman** [comment]
Hey Rex! This is because you’re defining HTML elements. Morphix works best with natural language queries since it’s made for non technical people. Can you please try things like “Title” and “Date Posted”?

This is best for extracting quick listed info, not collecting the full contents of pages.

------------
Alexa Kayman
------------

Bloom

alexakayman.com ( https://alexakayman.com/ )

New York, NY

twitter ( https://twitter.com/AlexaKayman )

linkedin ( https://www.linkedin.com/in/alexakayman/ )

Sent via Superhuman iOS ( ***@***.*** )
